# DOCUMENT VARIABLES

NAME= produto-modelo

# PROJECT VARIABLES

GZCAT= zcat
USE_PDFLATEX= true # directly generate .pdf files from the .tex
VIEWPDF= evince
MAKEGLS= makeglossaries

include /usr/share/latex-mk/latex.gmk
